execute:
  freeze: auto

project:
  type: website
  resources:
    - CNAME
    - tareas/**/*.ipynb
  render:
    - "*.qmd"
    - "slides/**/*.qmd"
    - "!quizzes/"
    - "!labs/"

website:
  title: "UCB NLP"

format:
  html:
    theme: cosmo
